### ISSUE TITLE
Using intro/api/ functionality

### ISSUE THREAD

**Issue by RoyMudie** [carlganz/rintrojs#37]
There's a couple of features that appear to be missing from rintrojs.

Specifically I want to have additional buttons on the page that start the introjs from a perticular step. The docs for introjs (https://introjs.com/docs/intro/api/) suggest that I should be able to use "introJs.goToStep(step)" but I don't seen any way of invoking this.

Any suggestions as to how I can acheive this when I've got my introjs programatical defined (also due to the fact I couldn't figure out how to get two instances of introjs on the same page as the targetElm parameter doesn't appear to be implemented either)

Cheers,
Roy

**Comment by carlganz** [comment]
Like I said in the other thread, if you want dynamic control over how your intros display you are much better off defining them in the server, rather than trying to get the javascript to work with two different static intros. 

That being said there I can certainly add the selector parameter like you asked for in other thread. If you want to work with the other functions in the introjs API it probably makes sense to write the Javascript yourself in the callbacks, unless I really don't understand your use case. 

If you can please provide me with a minimal example with plain HTML/Javascript of how the introjs API supports multiple static intros using the selector I can go ahead and add to this library. I did a little toying around with it on my own just now but wasn't able to get it to work. Thanks!

**Comment by carlganz** [comment]
Please reopen when you provide a minimal example of what you want `rintrojs` to do. Thanks
