### ISSUE TITLE
rintrojs in a deployed shiny app that includes tabPanels 

### ISSUE THREAD

**Issue by vaelliott** [carlganz/rintrojs#38]
I've been using the rintrojs package to build guidance to users of a shiny app.  I managed to write a script generates a tour with datasteps explaining features on different tabPanels within the app, this code works fine when run on RStudio locally but fails when the app is deployed.   

I'm not sure if my approach is not right one or if there is an issue when the app is deployed.  I've created a reprex and stack overflow request that describes in more detail the issue.

https://stackoverflow.com/questions/57787974/how-to-fix-rintrojs-modals-working-locally-but-fail-when-deployed-to-shinyapps-i

**Comment by carlganz** [comment]
I can see JavaScript error in console when I run your deployed copy so that should be enough for me to debug. I'll get back to you in a day or two with a fix hopefully. Thanks!

**Comment by vaelliott** [comment]
Any suggestions you have would be most appreciated, I'm guessing a fix is more complicated than maybe you'd hoped?

**Comment by carlganz** [comment]
Sorry for delayed response.

This is a bit tricky and I think is beyond the scope of `rintrojs` since it seems to only appear when deployed to ShinyApps.io

Here is what I can determine from [the app you deployed](https://scotland.shinyapps.io/scotpho-bug-test/). Whenever the tabs are switched back and forth the "href" property for the associated "a" html object changes to include the full URL of the website. This doesn't appear to happen locally, but it breaks the CSS selector that jQuery is using to automate the tab change during the intro.js tour.

@wch @jcheng5 Do you know if changing the href property of tabPanels to include full url is deliberate/desired feature for ShinyApps.io.

**Comment by vaelliott** [comment]
Thanks so much for investigating, we created a work around for now. Starting to try and learn a bit of javascript so maybe we can figure an alternative approach.

**Comment by jsinnett** [comment]
@vaelliott - Any chance you'd mind sharing your work around? I'm running into a similar issue. Thanks!

**Comment by carlganz** [comment]
I strongly encourage anyone who sees this issue to file a support ticket with RStudio if you are experiencing this issue on one of their Enterprise deployment tools.
