### ISSUE TITLE
Add Methods to reference existing UI elements for shinydashboard

### ISSUE THREAD

**Issue by DavZim** [carlganz/rintrojs#48]
Just wanted to get your feedback on this idea. 
I was trying to have a simple shinydashboard app, using the approach where the steps are created outside of shiny, referencing the element ids to separate the steps.

This does not work out of the box [see also this SO question](https://stackoverflow.com/questions/57183990/combining-rintrojs-with-shinydashboard/62701600). One workaround I found is to add a class-item to the respective UI element ([see my answer to the SO question](https://stackoverflow.com/a/62701600/3048453)).

The idea would be to have two new functions `add_class()` which adds a class to a shiny element, and `guess_id()` which tries to extract the class-id from a given UI.
These two functions would allow a workflow like this:

```r
# using add_class() to make the element reference-able by introjs, source code below
ui <- dashboardPage(
  # ... 
  sidebarMenu(
    menuItem("Menu 1", tabName = "view_1") %>% add_class(),
    actionButton("help", "Start IntroJS") %>% add_class()
  ),
  #...
  tabItem(tabName = "view_1",
    # box does not have an id, set manually or use `box(..., id = "box1") %>% add_class()`
    box(title = "The title") %>% add_class("box1") 
  ) %>% add_class()
  #...
steps <- data.frame(
  element = c(".view_1", ""),
  intro = c("A", "B")
)

server <- function(input, output, session) {
  observeEvent(input$help, introjs(session, options = list(steps = steps)))
}
#...
```

I tested the `guess_id()` function using the shiny widgets, shinydashboard and some other widgets like leaflet and DT [here](https://gist.github.com/DavZim/43498cf33f69b936d2bd5945fb5631a7).

What do you think of this approach?

## Full Example

```r
library(shinydashboard)
library(rintrojs)

# Tries to extract the ID value of a HTML shiny.tag
#
# If no ID is found, an NA is returned
# @param x a shiny.tag
#
# @return the ID tag, or NA if nothing is found
# @export
#
# @examples
# library(magrittr)
# textOutput("ID-TEXT") %>% guess_id()
# verbatimTextOutput("ID-TEXT") %>% guess_id()
# menuItem("text", tabName = "ID-MENU-ITEM") %>% guess_id()
# plotOutput("ID-PLOT") %>% guess_id()
# dataTableOutput("ID-DT") %>% guess_id()
guess_id <- function(x) {
  stopifnot(any(class(x) %in% c("shiny.tag", "shiny.tag.list")))
  ll <- unlist(x)
  match <- grepl("\\.id$", names(ll))
  if (any(match)) {
    return(as.character(ll[match])[1])
  } else {
    match <- grepl("\\.data-value$", names(ll))
    if (any(match)) return(as.character(ll[match])[1])
  }
  return(NA)
}

# Adds Class to an UI element
# 
# This allows accessing this element from introjs
#
# @param x a shiny UI element
# @param class_id A class id, which can be used from introjs, default is to guess the value using \code{guess_id()}
#
# @return
# @export
#
# @examples
# ui <- bootstrapPage(
#   numericInput('n', 'Number of obs', n) %>% add_class("n"), # manually set the class-id to "n"
#   plotOutput('plot') %>% add_class() # guess the id to be "plot"
# )
add_class <- function(x, class_id = guess_id(x)) {
  stopifnot(any(class(x) %in% c("shiny.tag", "shiny.tag.list")))
  x$attribs <- append(x$attribs, list(class = class_id))
  if (is.na(class_id)) stop("class_id is NA, maybe guess_id could not determine the ID of x")
  x
}

steps <- tibble::tribble(
  ~element, ~intro,
  NA, "First Empty State",
  ".main-header", "This is the header",
  ".view_1", "First Item",
  ".help", "This Help Button",
  ".first_box", "A shinydashboard box",
  ".num_points", "Add your desired number of points here",
  ".plot1", "A Plot",
)

ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(
    sidebarMenu(
      menuItem("Menu 1", tabName = "view_1") %>% add_class(), #<<<< add_class here
      actionButton("help", "Start IntroJS") %>% add_class() #<<<< add_class here
    )
  ),
  dashboardBody(
    introjsUI(),
    tabItems(
      tabItem(tabName = "view_1",
              box(title = "A first Box", id = "first_box", # <<<< set id here or in the add_class("first_box") later
                  sliderInput("num_points", "Number of Points", 100, 1000, step = 100, value = 100) %>% add_class(), # <<<<< add_class here
                  plotOutput("plot1") %>% add_class(), #<<<<<< add_class here
              ) %>% add_class() #<<<<<< add_class here
      )
    )
  )
)

server <- function(input, output, session) {
  output$plot1 <- renderPlot(hist(rnorm(input$num_points)))
  observeEvent(input$help, introjs(session, options = list(steps = steps)))
}

shinyApp(ui, server)
```

**Comment by carlganz** [comment]
Thanks for the thoughts!

This issue probably belongs in the htmltools package and is only loosely related to this package. Some thoughts hopefully in logical order:

* In regards to the error message in the Stackoverflow issue, `intro_box` is only designed to work with `shiny` objects and `shinydashboard` has a few special objects that don't work like `dashboardSidebar`. Ultimately if you want to display the contents of your sidebar the `intro_box` should go inside the dashboardSidebar and wrap a `span` or `div` that contains the contents of the sidebar. 
* As the other SO answer suggests, in cases when packages like `shinydashboard` give you objects that don't let you directly manipulate the id you can often find a different workable CSS selector.
* Your function that takes IDs and puts them into classes doesn't add any value from a CSS selector perspective. Anything with an ID can just as easily be selected by that ID as it can be by class. The helper functions you provided are solving the issue because they are taking the ID or data-value in the nested html and adding to the class of the outer most html object, which as you pointed out in the SO answer `shinydashboard` provides no interface for manipulating the outer `li` tag in `menuItem`. 
* As far as I can tell the main issue has to do with functions like `menuItem` which are wrappers around htmltools. These wrappers aren't providing you with an interface to manipulate the classes and ids of the underlying html objects. My advice would be to use htmltools directly and bulid the menu item with the parameters you need so you can apply an id or class to the underlying `li` tag or any of the other underlying tags exactly as you desire. The whole point of the htmltools package is to give you a granular interface to html in shiny whenever the shiny or shinydashboard wrappers are too naive, as they are in the use case you presented. 
* The folks at htmltools might like what you have and think it is useful to have some additional tools for manipulating html objects, but ultimately I don't think there is anything to fix on the `rintrojs` side.

Thanks again!
