### ISSUE TITLE
customizing width of tooltip

### ISSUE THREAD

**Issue by thercast** [carlganz/rintrojs#5]
Before I go on I want to say a huge thank you for making this package!  I first was exposed to `intro.js` during Herman Sontrop's [talk](https://www.rstudio.com/resources/videos/friss/) at [ShinyDevCon](https://www.rstudio.com/resources/webinars/shiny-developer-conference/) and I've been wanting to incorporate this functionality in to my Shiny apps ever since.  

One feature that would be useful is customizing the width of the tooltip in case we have to show a lot of text.  In particular I've experimented with including HTML parsed from markdown text via supplying a call to `includeMarkdown` as the value for `data.intro` (see [this gist](https://gist.github.com/thercast/dcb36373a1f3847cf168b7072e784a72)).  I've read about one of the options called `tooltipClass` that [may work](https://github.com/usablica/intro.js/issues/326) but I wasn't able to track down a simple example of how to use this the way I'm intending.  Any insights would be greatly appreciated.

**Comment by carlganz** [comment]
Hey, thanks a lot for the feedback. I will investigate this thoroughly this weekend and respond then.

Regards,
Carl

**Comment by carlganz** [comment]
Hello @thercast,

Here is what I have been able to identify about tooltip width:

- By default, the CSS class has parameters `width-min` and `width-max` pre-set. You can change those values those with CSS. `Introjs` tries to be smart and will make the the width of the tooltip proportional to the size of the element it is introducing. If you use percents in the min or max CSS it is the percent of the width of the div it is introducing, so I recommend hard coding with px. 

- In the example in your gist, you probably want a really wide box for the first step, and a regular sized box for the rest. If you include in the beginning of your `fluidPage`

```{R}
  tags$style(HTML(
    ".introjs-tooltip {
      max-width: 100%;
      min-width: 500px;
    }"
  ))
```

But this a hack, and won't work in general, because the 100% is relative to the element being introduced so if the first element was a button instead of a title it would be a problem.

- What we really want is a way to directly control the width of each step. As the issue you mentioned points out, this is not really a straight forward thing to do in `Intro.js`. The best thing I can think of is to control the `max/min-width` in the `onbeforechange` event for each step.

- Here is a JSfiddle that demonstrates how to control `Intro.js` widths for each step with `onbeforechange`: https://fiddle.jshell.net/ya6km785/3/

- First you use `tooltipClass` to create your own CSS class for the tooltip. Using CSS set the `max/min-width` equal to the size you want for the first tooltip. Then change the CSS using javascript based on each step number. 

- There was a bug in `rintrojs`, so to use events you need to install the dev version from Github. Then this version of your example should work:

```{R}

# devtools::install_github("carlganz/rintrojs")
library(rintrojs)
library(shiny)

# Define UI for application that draws a histogram
ui <- shinyUI(fluidPage(
  introjsUI(),
  tags$style(HTML(
    ".newClass {
      min-width: 800px;
      max-width: 800px;
    }"
  )),
  # Application title
  introBox(
    titlePanel("Old Faithful Geyser Data"),
    data.step = 1,
    data.intro = includeMarkdown("test.md")
  ),
  
  # Sidebar with a slider input for number of bins
  sidebarLayout(sidebarPanel(
    introBox(
      introBox(
        sliderInput(
          "bins",
          "Number of bins:",
          min = 1,
          max = 50,
          value = 30
        ),
        data.step = 3,
        data.intro = "This is a slider",
        data.hint = "You can slide me"
      ),
      introBox(
        actionButton("help", "Press for instructions"),
        data.step = 4,
        data.intro = "This is a button",
        data.hint = "You can press me"
      ),
      data.step = 2,
      data.intro = "This is the sidebar. Look how intro elements can nest"
    )
  ),
  
  # Show a plot of the generated distribution
  mainPanel(
    introBox(
      plotOutput("distPlot"),
      data.step = 5,
      data.intro = "This is the main plot"
    )
  ))
))

# Define server logic required to draw a histogram
server <- shinyServer(function(input, output, session) {
  # initiate hints on startup with custom button and event
  hintjs(session, options = list("hintButtonLabel"="Hope this hint was helpful"),
         events = list("onhintclose"='alert("Wasn\'t that hint helpful")'))
  
  output$distPlot <- renderPlot({
    # generate bins based on input$bins from ui.R
    x    <- faithful[, 2]
    bins <- seq(min(x), max(x), length.out = input$bins + 1)
    
    # draw the histogram with the specified number of bins
    hist(x,
         breaks = bins,
         col = 'darkgray',
         border = 'white')
  })
  
  # start introjs when button is pressed with custom options and events
  observeEvent(input$help,
               introjs(session, options = list("nextLabel"="Onwards and Upwards",
                                               "prevLabel"="Did you forget something?",
                                               "skipLabel"="Don't be a quitter",
                                               "tooltipClass"="newClass"),
                       events = list("oncomplete"='alert("Glad that is over")',
                                     "onbeforechange"='
                                     if (targetElement.getAttribute("data-step")==="1") {
                                      $(".newClass").css("max-width", "800px").css("min-width","800px");  
                                     } else {
                                      $(".newClass").css("max-width", "500px").css("min-width","500px");
                                     }'))
  )
})

# Run the application
shinyApp(ui = ui, server = server)

```

Let me know if you have any questions.

Kind Regards,
Carl

**Comment by thercast** [comment]
Thanks Carl!  I just upgraded `rintrojs` and the revised example works very well.   If I'm understanding correctly, I should define a new CSS class for the max and min widths of the tooltips early on in the app UI, and then in the  `introjs()` events processing utilize javascript conditionals to check if the data step is one I want to have a larger width set or not.  In future apps it may not be the first step, so I'll just adapt as needed.

**Comment by carlganz** [comment]
Yeah that's the right idea. Let me know if you have any further questions.
